### ISSUE TITLE
Missing csv files for dialogue engine

### ISSUE THREAD

**Issue by erikbilling** [igor-lirussi/Dialogue-Pepper-Robot#1]
Hi Igor, 

I’m a researcher at the university of Skövde working with the Pepper robot. We found your dialogue system for Pepper on GitHub, https://github.com/igor-lirussi/Dialogue-Pepper-Robot, and we’re now trying to get it to run for our robot. 

The dialogue engine Ab.jar gives exceptions from not finding csv files, one for each aiml file. I attach the trace from the first three exceptions below. Is there a chance you could add the missing csv:s to this repo or give other directions for how to get the dialogue engine running? 
----
... Dialogue-Pepper-Robot $ java -cp lib/Ab.jar Main bot=en
Working Directory = /Users/sander/Source/Dialogue-Pepper-Robot
Program AB 0.0.4.2 beta -- AI Foundation Reference AIML 2.0 implementation
bot=en
trace mode = false
Name = en Path = /Users/sander/Source/Dialogue-Pepper-Robot/bots/en
/Users/sander/Source/Dialogue-Pepper-Robot
/Users/sander/Source/Dialogue-Pepper-Robot/bots
/Users/sander/Source/Dialogue-Pepper-Robot/bots/en
/Users/sander/Source/Dialogue-Pepper-Robot/bots/en/aiml
/Users/sander/Source/Dialogue-Pepper-Robot/bots/en/aimlif
/Users/sander/Source/Dialogue-Pepper-Robot/bots/en/config
/Users/sander/Source/Dialogue-Pepper-Robot/bots/en/logs
/Users/sander/Source/Dialogue-Pepper-Robot/bots/en/sets
/Users/sander/Source/Dialogue-Pepper-Robot/bots/en/maps
Preprocessor: 416 norms 56 persons 9 person2 
Get Properties: /Users/sander/Source/Dialogue-Pepper-Robot/bots/en/config/properties.txt
Exists: /Users/sander/Source/Dialogue-Pepper-Robot/bots/en/config/properties.txt
Loading AIML Sets files from /Users/sander/Source/Dialogue-Pepper-Robot/bots/en/sets
mammal.txt
Read AIML Set mammal
Reading AIML Set /Users/sander/Source/Dialogue-Pepper-Robot/bots/en/sets/mammal.txt
bird.txt
Read AIML Set bird
Reading AIML Set /Users/sander/Source/Dialogue-Pepper-Robot/bots/en/sets/bird.txt
fastfood.txt
Read AIML Set fastfood
Reading AIML Set /Users/sander/Source/Dialogue-Pepper-Robot/bots/en/sets/fastfood.txt
verb2st.txt
Read AIML Set verb2st
Reading AIML Set /Users/sander/Source/Dialogue-Pepper-Robot/bots/en/sets/verb2st.txt
place.txt
Read AIML Set place
Reading AIML Set /Users/sander/Source/Dialogue-Pepper-Robot/bots/en/sets/place.txt
preposition.txt
Read AIML Set preposition
Reading AIML Set /Users/sander/Source/Dialogue-Pepper-Robot/bots/en/sets/preposition.txt
verb2sp.txt
Read AIML Set verb2sp
Reading AIML Set /Users/sander/Source/Dialogue-Pepper-Robot/bots/en/sets/verb2sp.txt
familiarname.txt
Read AIML Set familiarname
Reading AIML Set /Users/sander/Source/Dialogue-Pepper-Robot/bots/en/sets/familiarname.txt
name.txt
Read AIML Set name
Reading AIML Set /Users/sander/Source/Dialogue-Pepper-Robot/bots/en/sets/name.txt
ordinal.txt
Read AIML Set ordinal
Reading AIML Set /Users/sander/Source/Dialogue-Pepper-Robot/bots/en/sets/ordinal.txt
digit.txt
Read AIML Set digit
Reading AIML Set /Users/sander/Source/Dialogue-Pepper-Robot/bots/en/sets/digit.txt
color.txt
Read AIML Set color
Reading AIML Set /Users/sander/Source/Dialogue-Pepper-Robot/bots/en/sets/color.txt
mammalfeature.txt
Read AIML Set mammalfeature
Reading AIML Set /Users/sander/Source/Dialogue-Pepper-Robot/bots/en/sets/mammalfeature.txt
language.txt
Read AIML Set language
Reading AIML Set /Users/sander/Source/Dialogue-Pepper-Robot/bots/en/sets/language.txt
profile.txt
Read AIML Set profile
Reading AIML Set /Users/sander/Source/Dialogue-Pepper-Robot/bots/en/sets/profile.txt
Loading AIML Map files from /Users/sander/Source/Dialogue-Pepper-Robot/bots/en/maps
ordinal2number.txt
Read AIML Map ordinal2number
Reading AIML Map /Users/sander/Source/Dialogue-Pepper-Robot/bots/en/maps/ordinal2number.txt
profile2predicate.txt
Read AIML Map profile2predicate
Reading AIML Map /Users/sander/Source/Dialogue-Pepper-Robot/bots/en/maps/profile2predicate.txt
number2ordinal.txt
Read AIML Map number2ordinal
Reading AIML Map /Users/sander/Source/Dialogue-Pepper-Robot/bots/en/maps/number2ordinal.txt
verb2sp2verb1sp.txt
Read AIML Map verb2sp2verb1sp
Reading AIML Map /Users/sander/Source/Dialogue-Pepper-Robot/bots/en/maps/verb2sp2verb1sp.txt
familiarpredicate.txt
Read AIML Map familiarpredicate
Reading AIML Map /Users/sander/Source/Dialogue-Pepper-Robot/bots/en/maps/familiarpredicate.txt
gendername.txt
Read AIML Map gendername
Reading AIML Map /Users/sander/Source/Dialogue-Pepper-Robot/bots/en/maps/gendername.txt
AIML modified Mon Apr 11 13:59:35 CEST 2022 AIMLIF modified Thu Jan 01 01:00:00 CET 1970
No deleted.aiml.csv file found
No deleted.aiml.csv file found
AIML modified after AIMLIF
Loading AIML files from /Users/sander/Source/Dialogue-Pepper-Robot/bots/en/aiml
shutup.aiml
knockknock.aiml
utilities.aiml
train.aiml
happy.aiml
jokes.aiml
dialog.aiml
drphil.aiml
seasons.aiml
horoscope.aiml
categoryProcessor: unexpected think
favorites.aiml
reductions1.aiml
recommendations.aiml
binary.aiml
update.aiml
udc.aiml
reductions_update.aiml
familiar.aiml
sraix.aiml
yomama.aiml
gender.aiml
bot_profile.aiml
copyme.aiml
filterinsults.aiml
date.aiml
limericks.aiml
client_profile.aiml
that.aiml
personality.aiml
inquiry.aiml
filterprofanity.aiml
onthisday.aiml
ontology.aiml
currency.aiml
filerinappropriate.aiml
Loaded 9255 categories in 0.975 sec
writeAIMLIFFiles
java.io.FileNotFoundException: /Users/sander/Source/Dialogue-Pepper-Robot/bots/en/aimlif/shutup.aiml.csv (No such file or directory)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:293)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:235)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:123)
	at java.base/java.io.FileWriter.<init>(FileWriter.java:66)
	at org.alicebot.ab.Bot.writeAIMLIFFiles(Bot.java:403)
	at org.alicebot.ab.Bot.<init>(Bot.java:135)
	at Main.mainFunction(Main.java:57)
	at Main.main(Main.java:36)
java.io.FileNotFoundException: /Users/sander/Source/Dialogue-Pepper-Robot/bots/en/aimlif/shutup.aiml.csv (No such file or directory)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:293)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:235)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:123)
	at java.base/java.io.FileWriter.<init>(FileWriter.java:66)
	at org.alicebot.ab.Bot.writeAIMLIFFiles(Bot.java:403)
	at org.alicebot.ab.Bot.<init>(Bot.java:135)
	at Main.mainFunction(Main.java:57)
	at Main.main(Main.java:36)
java.io.FileNotFoundException: /Users/sander/Source/Dialogue-Pepper-Robot/bots/en/aimlif/shutup.aiml.csv (No such file or directory)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:293)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:235)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:123)
	at java.base/java.io.FileWriter.<init>(FileWriter.java:66)
	at org.alicebot.ab.Bot.writeAIMLIFFiles(Bot.java:403)
	at org.alicebot.ab.Bot.<init>(Bot.java:135)
	at Main.mainFunction(Main.java:57)
	at Main.main(Main.java:36)
….

**Comment by erikbilling** [comment]
This issue can be fixed by manually creating the folder `aimlif` in `bots/en`.

**Comment by igor-lirussi** [comment]
Updated the ReadME with the solution :)
